-- Alzahraa Candles database schema - matched to the current database you shared.
-- For an existing live database, prefer running existing-database-migration.sql.
-- Use this file only for a fresh Supabase project or as documentation.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  phone text,
  governorate text,
  address text,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.profiles
  add column if not exists role text not null default 'customer';

alter table if exists public.profiles
  drop constraint if exists profiles_role_check;

alter table if exists public.profiles
  add constraint profiles_role_check check (role in ('customer', 'admin'));

create table if not exists public.products (
  id bigint generated always as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  price numeric not null default 0,
  image text,
  category text default 'all',
  description text,
  badge text,
  tag text,
  best_for text,
  weight text default '120 جرام',
  long_description text,
  highlights jsonb default '[]'::jsonb,
  benefits jsonb default '[]'::jsonb,
  ingredients jsonb default '[]'::jsonb,
  usage text,
  slug text,
  short_description text,
  fabric text,
  care_note text,
  size_guide text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  size_label text not null,
  color_name text not null,
  color_hex text,
  price numeric not null check (price >= 0),
  compare_price numeric,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  sku text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  color_name text,
  image_path text not null,
  alt_text text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated always as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text,
  phone text,
  city text,
  notes text,
  items_json jsonb,
  total numeric,
  status text default 'pending' check (status is null or status in ('pending', 'confirmed', 'processing', 'delivered', 'cancelled')),
  source text default 'website',
  order_number text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  customer_email text,
  delivery_lat double precision,
  delivery_lng double precision,
  delivery_maps_link text,
  delivery_location_source text
);

create index if not exists idx_products_active_sort on public.products (is_active, sort_order, id);
create index if not exists idx_product_variants_product_active_sort on public.product_variants (product_id, is_active, sort_order, id);
create index if not exists idx_product_images_product_active_sort on public.product_images (product_id, is_active, sort_order, id);
create index if not exists idx_orders_user_created on public.orders (user_id, created_at desc);
create index if not exists idx_orders_status_created on public.orders (status, created_at desc);
create index if not exists idx_orders_number on public.orders (order_number);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at before update on public.products for each row execute function public.set_updated_at();

drop trigger if exists trg_product_variants_updated_at on public.product_variants;
create trigger trg_product_variants_updated_at before update on public.product_variants for each row execute function public.set_updated_at();

drop trigger if exists trg_product_images_updated_at on public.product_images;
create trigger trg_product_images_updated_at before update on public.product_images for each row execute function public.set_updated_at();

drop view if exists public.orders_dashboard;
create view public.orders_dashboard
with (security_invoker = true) as
select
  o.id,
  o.order_number,
  o.customer_name,
  o.phone,
  o.city,
  o.notes,
  o.items_json,
  o.total,
  o.status,
  o.source,
  o.created_at,
  o.user_id,
  o.customer_email,
  o.delivery_lat,
  o.delivery_lng,
  o.delivery_maps_link,
  o.delivery_location_source,
  coalesce(jsonb_array_length(o.items_json), 0) as items_count,
  coalesce(jsonb_array_length(o.items_json), 0) as line_items_count
from public.orders o;

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_create_profile on auth.users;
create trigger on_auth_user_created_create_profile
after insert on auth.users
for each row execute function public.handle_new_user_profile();
